version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, go]

  - package-ecosystem: npm
    directory: /frontend-admin
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, npm]

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies, ci]

  - package-ecosystem: pub
    directory: /mobile
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies, flutter]
